
# https://docs.zephyrproject.org/3.1.0/develop/west/manifest.html

# https://github.com/zephyrproject-rtos/zephyr/issues/35075

manifest:

  self:
    path: zephyr-trinamic

  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
    - name: trinamic
      url-base: https://github.com/cooked

  projects:
    - name: zephyr
      remote: zephyr
      repo-path: zephyr
      revision: main
      import:
        name-allowlist:
          - cmsis
          - hal_stm32

    - name: hal_tmc
      remote: trinamic
      repo-path: TMC-API
      path: modules/hal/tmc
      revision: zephyr
