manifest:

  self:
    path: zephyr-trinamic

  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
    - name: trinamic
      url-base: https://github.com/cooked

  projects:
    - name: zephyr
      remote: zephyr
      revision: main
      path: rtos
      import:
        name-allowlist:
          - cmsis
          - hal_stm32

    - name: hal_tmc
      remote: trinamic
      repo-path: TMC-API
      path: modules/hal/tmc
      revision: zephyr
